#!/usr/bin/python3

import argparse
import rmtadm

parser = argparse.ArgumentParser(description="rmtadm server toolkit")
subparsers = parser.add_subparsers(dest="cmd", required=True)

connect = subparsers.add_parser("connect", help="Connect to a connected client")
connect.add_argument("client_hostname", type=str, help="Hostname of the client")

list = subparsers.add_parser("list", help="Show all connected clients")

argvals = vars(parser.parse_args())

cmd = argvals['cmd']

if cmd == 'connect':
    rmtadm.connect(argvals['client_hostname'])
elif cmd == 'list':
    rmtadm.list()

